#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:          v2ray is a lightweight multi-protocol & multi-source command-line download utility.
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: v2ray is a lightweight multi-protocol & multi-source command-line download utility.
# Description:       Start or stop the v2ray
### END INIT INFO

#PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
#export PATH
do_start() {
/usr/bin/v2ray -config /usr/local/etc/v2ray/config.json >/dev/null 2>&1 &
echo -e "ok"
}
do_stop() {
kill -9 $(pidof v2ray)
echo -e "stop"
}
do_restart() {
	do_stop
	do_start
}
case "$1" in
start | stop | restart)
	do_$1
	;;
*)
	echo "使用说明: $0 { start | stop | restart}"
	RETVAL=1
	;;
esac
exit $RETVAL
