name: go docker
on:
  #schedule:
    #- cron: 10 22 * * *
  watch:
    types: started       
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wget
        sudo apt-get -y install curl
    - name: login docker
      run: |
        cd /home/runner
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: docker ssv2ray
      run: |
        cd /home/runner/work/docker/docker/ssv2ray
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ssv2ray .
        docker push ${{ secrets.DOCKER_USERNAME }}/ssv2ray
    - name: docker gdbot
      run: |
        cd /home/runner/work/docker/docker/gdbot
        docker build -t ${{ secrets.DOCKER_USERNAME }}/gdbot .
        docker push ${{ secrets.DOCKER_USERNAME }}/gdbot
    - name: docker v2tls-docker
      run: |
        cd /home/runner/work/docker/docker/v2tls-docker
        docker build -t ${{ secrets.DOCKER_USERNAME }}/v2tls-docker .
        docker push ${{ secrets.DOCKER_USERNAME }}/v2tls-docker        
    - name: docker ibm-docker
      run: |
        cd /home/runner/work/docker/docker/ibm-docker
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ibm-docker .
        docker push ${{ secrets.DOCKER_USERNAME }}/ibm-docker
    - name: docker qbdown
      run: |
        cd /home/runner/work/docker/docker/qbdown
        docker build -t ${{ secrets.DOCKER_USERNAME }}/qbdown .
        docker push ${{ secrets.DOCKER_USERNAME }}/qbdown
    - name: docker aria2-docker
      run: |
        cd /home/runner/work/docker/docker/aria2-docker
        docker build -t ${{ secrets.DOCKER_USERNAME }}/aria2-docker .
        docker push ${{ secrets.DOCKER_USERNAME }}/aria2-docker        
